### ISSUE TITLE
Latest version?

### ISSUE THREAD

**Issue by rg-one-two** [WayneGitShell/sstCalculation#1]
Dear FINMA, This repository was an amazing find for me since I work on Mac and was able to build the sstCalculation package (I could not use the version on the FINMA site as it seems to only be for windows) and start the sstDashboard(). However, the dashboard will not run:

Error
- A newer version of the R-Tool is required to process this SST-Template. Please use the latest version of the R-Tool provided by FINMA.More details and guidance about the R-Tool are available on FINMA's website.

Would it be possible that you push the version 2.5.0 to this github?

Thanks a lot!

**Comment by WayneGitShell** [comment]
Sorry- but this is a copy of a repo I cloned for testing purposes and I'm not the original author. Suggest you contact FINMA directly.

**Comment by WayneGitShell** [comment]
See link here: https://www.finma.ch/en/~/media/finma/dokumente/dokumentencenter/myfinma/2ueberwachung/sst/it_notizen.pdf?sc_lang=en&hash=F4AE1C7C43178B0FAB3D918C4AD9750D
